# Uncomment the next line to define a global platform for your project
# platform :ios, '12.0'

target 'NewsApi' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NewsApi
pod 'SnapKit', '~> 5.7.0'
pod 'AlamofireImage', '~> 4.1'

end
